name: Earle
description: Earle project

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  fancy_bottom_navigation: ^0.3.2
  http: ^0.12.0+2
  json_annotation: ^2.0.0
  transparent_image: ^1.0.0
  camera:
  path_provider:
  path:
  image_picker: ^0.6.0+9
  google_maps_flutter: ^0.5.15
  image: ^2.1.4
  location: ^2.3.5
  flutter_launcher_icons: ^0.7.0
  toast: ^0.1.4
  shared_preferences: ^0.5.3+1
  enum_to_string: ^1.0.7
  datetime_picker_formfield: ^0.2.0
  dotted_border: ^0.1.1
  cached_network_image: ^1.0.0
  flutter_spinkit: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon.png"
  image_path_android: "assets/icon.png"
flutter:

  uses-material-design: true

  assets:
    - icon.png
    - logo.png
    - login-background.png
    - thumbnail-frame.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
